/*
  This file was auto-generated by Jinno.
*/
  
// "Primary" story - auto generated by Jinno.
export const Primary = {
  // 👇 You can add your component props to here
  args: {
    onLog: (...args: any[]) => 'Jinno is Awesome',
    onBacktestCompleted: (...args: any[]) => 'Jinno is Awesome',
    onStrategySelected: (...args: any[]) => 'Jinno is Awesome',
    selectedStrategyName: "Jinno is Awesome",
    title: "example",
    value: "example",
    subValue: "example",
    icon: "Jinno is Awesome",
    trend: "Jinno is Awesome",
  },
};

// 👇 You can add more story types if you like for your component
export const Secondary = {
  args: {
  },
};

// 👇 This tells Jinno which story to render.
export const selectedScenario = Primary;
  